chore: pagination enhancement
juspay/hyperswitch-control-center pull request #1093
Opened 2024-07-30 17:59 UTC by sagarnaikjuspay

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
New pagination design and compoment enhancement 
![image](https://github.com/user-attachments/assets/02a7db40-cc5a-4c1d-84a8-4139f3124f99)

## Motivation and Context

## How did you test it?

## Where to test it?
- [ ] INTEG
- [ ] SANDBOX
- [ ] PROD

## Checklist

- [ ] I ran `npm run re:build`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible

2024-07-30 19:06 UTC, PritishBudhiraja commented on src/screens/Payouts/PayoutsList.res
> +    let newDict = pageDetailDict->Dict.toArray->Dict.fromArray
newDict->DictionaryUtils.copyOfDict

2024-07-30 19:13 UTC, PritishBudhiraja commented on src/screens/Payouts/PayoutsList.res
> +    newDict->Dict.set("Payouts", defaultValue)
And why we are manipulating a state like this? As pageDetailDict is an atomvalue it should have been done like this please try this - 
```
    setPageDetails(prev => {
      let newDict = prev->DictionaryUtils.copyOfDict
      newDict->Dict.set("Payouts", defaultValue)
      newDict
    })
```

2024-07-30 19:13 UTC, PritishBudhiraja requested changes
And why we are manipulating a state like this everywhere? As pageDetailDict is an atom value it should have been done like this please try this -
```
    setPageDetails(prev => {
      let newDict = prev->DictionaryUtils.copyOfDict
      newDict->Dict.set("Payouts", defaultValue)
      newDict
    })
```

2024-07-30 19:23 UTC, PritishBudhiraja commented on src/components/Paginator.res
> +  ~actualData as _,
if not using remove it

2024-07-30 19:32 UTC, PritishBudhiraja commented on src/components/Paginator.res
> +    }
```
let pageNumbers = Array.fromInitializer(~length=total, i => i + 1)
```

2024-07-31 06:20 UTC, Riddhiagrawal001 commented on src/components/Paginator.res
> +                  }
setArrow(_=> props["open"])

2024-07-31 06:20 UTC, Riddhiagrawal001 commented on src/components/Paginator.res
> +                  }
same here

2024-07-31 06:20 UTC, Riddhiagrawal001 commented on src/screens/Order/Orders.res
> +    let newDict = pageDetailDict->Dict.toArray->Dict.fromArray
Do we need this `->Dict.toArray->Dict.fromArray `

2024-07-31 06:20 UTC, Riddhiagrawal001 commented on src/screens/Refunds/Refund.res
> +    let newDict = pageDetailDict->Dict.toArray->Dict.fromArray
Same here `->Dict.toArray->Dict.fromArray `

2024-07-31 06:52 UTC, JeevaRamu0104 commented on src/components/Paginator.res
> +                    setArrow(_ => true)
please check whether your getting any warning in console.Because setState is happening at every render

2024-08-29 09:32 UTC, closed without merging