fix: Moved HyperLoader script
juspay/hyperswitch-control-center pull request #110
Opened 2023-12-18 16:00 UTC by vsrivatsa-juspay

Moved HyperLoader script to inside preview component, remove on clean-up function of useEffect

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I ran `npm run re:build`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible

2023-12-19 05:25 UTC, JeevaRamu0104 commented on src/screens/HyperSwitch/SDKPayment/SDKPage.res
> +    | Live => "https://checkout.hyperswitch.io/v0/HyperLoader.js"
rather than defining the url directly we should take from the env value for the sdk url

2023-12-28 09:18 UTC, PritishBudhiraja requested changes

2023-12-28 09:18 UTC, PritishBudhiraja commented on src/screens/HyperSwitch/SDKPayment/SDKPage.res
> +external appendChild: Dom.element => unit = "appendChild"
Add these window/DOM related things inside DOMUtils.res

2024-01-02 13:37 UTC, PritishBudhiraja submitted a review, later dismissed

2024-01-03 06:21 UTC, JeevaRamu0104 reviewed
@vsrivatsa-juspay SDK is breaking in the stripe+paypal flow in the quick start
<img width="1728" alt="image" src="https://github.com/juspay/hyperswitch-control-center/assets/120017870/3685af5a-e856-4544-9f30-83aded566ecf">

2024-01-03 06:27 UTC, JeevaRamu0104 reviewed
You need to move this logic to `WebSDK.res` file rather than having it on `SDKPage.res`

2024-01-03 11:38 UTC, Riddhiagrawal001 approved these changes

2024-01-05 08:52 UTC, vsrivatsa-juspay commented
> @vsrivatsa-juspay SDK is breaking in the stripe+paypal flow in the quick start <img alt="image" width="1728" src="https://private-user-images.githubusercontent.com/120017870/293845317-3685af5a-e856-4544-9f30-83aded566ecf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NDUwNjAsIm5iZiI6MTcwNDQ0NDc2MCwicGF0aCI6Ii8xMjAwMTc4NzAvMjkzODQ1MzE3LTM2ODVhZjVhLWU4NTYtNDU0NC05ZjMwLTgzYWRlZDU2NmVjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNVQwODUyNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjMyMDY5NTg2NjFiMjc5NzJkY2M1OTQ1YTFhYjg4YzdmZDhhZTBmZDAxNzNlYTliN2VkZDVjZmRmYWJmMzVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8CYOnpRLyjgvOUpTa1ASjBliH06AGk8NCa5Iaq_GCVk">

Moved to TestPayment.res

2024-01-10 10:36 UTC, JeevaRamu0104 approved these changes

2024-01-10 10:37 UTC, merged