chore: update profile dropdown
juspay/hyperswitch-control-center pull request #1434
Opened 2024-09-19 11:38 UTC by gitanjli525

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
added -  profile label for profile list dropdown
fixed - current profile name gets updated when profile name is edited in business profiles 
![image](https://github.com/user-attachments/assets/5da52d76-84ea-49dd-b1d1-cb92a5f9f2c6)
![image](https://github.com/user-attachments/assets/7643b245-5993-4de4-9582-f9ad97249af8)

## Motivation and Context
profile dropdown component changes

## How did you test it?
working as explained in description

## Where to test it?

- [ ] INTEG
- [ ] SANDBOX
- [ ] PROD

## Checklist

- [ ] I ran `npm run re:build`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible

2024-09-19 11:40 UTC, PritishBudhiraja approved these changes

2024-09-19 11:49 UTC, sagarnaikjuspay requested changes

2024-09-19 11:49 UTC, sagarnaikjuspay commented on src/screens/OMPSwitch/ProfileSwitch.res
> +      <div className="flex flex-row gap-2 px-2 py-2 fs-10">
`px-2 py-2` -> `p-2`

2024-09-19 11:50 UTC, sagarnaikjuspay commented on src/screens/OMPSwitch/ProfileSwitch.res
> +      <div className="flex flex-row gap-2 px-2 py-2 fs-10">
`px-2 py-2` -> `p-2`

2024-09-19 12:34 UTC, gitanjli525 commented on src/screens/OMPSwitch/ProfileSwitch.res
> +      <div className="flex flex-row gap-2 px-2 py-2 fs-10">
okay

2024-09-19 13:49 UTC, PritishBudhiraja approved these changes

2024-09-20 10:39 UTC, sagarnaikjuspay approved these changes

2024-09-20 10:51 UTC, merged