Filters enhance
juspay/hyperswitch-control-center pull request #160
Opened 2024-01-03 10:45 UTC by sagarnaikjuspay

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I ran `npm run re:build`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible

2024-01-03 11:07 UTC, Riddhiagrawal001 submitted a review, later dismissed

2024-01-04 01:53 UTC, JeevaRamu0104 commented on src/screens/HyperSwitch/HSwitchRemoteFilter.res
> +      if filterValueJson->Js.Dict.keys->Js.Array2.length <= 0 {
you can just check for empty dict

2024-01-04 06:09 UTC, PritishBudhiraja requested changes

2024-01-04 06:09 UTC, PritishBudhiraja commented on src/components/DateRangePicker.res
> +      startDateVal->Js.String2.length === 0 && endDateVal->Js.String2.length === 0
can we start using the rescript core changes from every PR?
For Reference - [Conversions](https://github.com/rescript-association/rescript-core/blob/main/migration/migration.toml)

2024-01-04 06:09 UTC, PritishBudhiraja commented on src/screens/HyperSwitch/HSwitchRemoteFilter.res
> +      if filterValueJson->Js.Dict.keys->Js.Array2.length <= 0 {
Same can we use the conversions.

2024-01-04 06:09 UTC, PritishBudhiraja commented on src/screens/HyperSwitch/HSwitchRemoteFilter.res
> +        setFilters(_ => Js.Dict.empty()->Some)
Same conversion.

2024-01-05 10:35 UTC, PritishBudhiraja commented on src/screens/HyperSwitch/HSwitchRemoteFilter.res
> +        setFilters(_ => Js.Dict.empty()->Some)
Dict.make()

2024-01-05 10:45 UTC, PritishBudhiraja approved these changes

2024-01-05 10:56 UTC, Riddhiagrawal001 commented on src/components/DateRangePicker.res
> +      startDateVal->String.length <= 0 && endDateVal->String.length <= 0
We can directly write `startDateVal->String.length === 0 && endDateVal->String.length === 0`

2024-01-08 10:52 UTC, Riddhiagrawal001 commented on src/screens/HyperSwitch/HSwitchRemoteFilter.res
> +      if filterValueJson->Js.Dict.keys->Js.Array2.length === 0 {
Please use core functions for Js.Dict.keys and Js.Array2.length

2024-01-08 10:52 UTC, Riddhiagrawal001 commented on src/screens/HyperSwitch/HSwitchRemoteFilter.res
> +      if filterValueJson->Js.Dict.keys->Js.Array2.length != 0 {
Please use core functions for Js.Dict.keys and Js.Array2.length

2024-01-09 04:55 UTC, JeevaRamu0104 approved these changes

2024-01-09 09:23 UTC, Riddhiagrawal001 approved these changes

2024-01-09 10:33 UTC, merged