feat: added new filters for payments
juspay/hyperswitch-control-center pull request #172
Opened 2024-01-05 07:46 UTC by sagarnaikjuspay

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

## Motivation and Context

## How did you test it?

## Checklist
![Screenshot 2024-01-05 at 1 14 05 PM](https://github.com/juspay/hyperswitch-control-center/assets/126486299/16654aa6-2533-4486-9bee-10f23d83a44e)

- [ ] I ran `npm run re:build`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible

2024-01-05 10:41 UTC, PritishBudhiraja requested changes

2024-01-05 10:41 UTC, PritishBudhiraja commented on src/screens/HyperSwitch/HSwitchRemoteFilter.res
> -      ->Array.filterWithIndex((_item, index) => index > 3)
We can have this check in the above filter only. 

`item.localFilter->Js.Option.isNone && index > 3`

2024-01-05 10:48 UTC, PritishBudhiraja approved these changes

2024-01-05 10:55 UTC, Riddhiagrawal001 approved these changes

2024-01-08 09:06 UTC, JeevaRamu0104 approved these changes

2024-01-08 09:09 UTC, merged