refactor:font size function refactor
juspay/hyperswitch-control-center pull request #342
Opened 2024-02-05 13:37 UTC by Riddhiagrawal001

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [X] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I ran `npm run re:build`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible

2024-02-05 13:43 UTC, PritishBudhiraja commented on src/components/HSwitchSingleStatWidget.res
> +            <div className={`${HSwitchUtils.getTextClass((H3, Leading_2))} text-grey-700`}>
Why to remove named paramters?
It's better to have name parameters

2024-02-05 13:45 UTC, PritishBudhiraja requested changes
Why to remove named paramters?
It's better to have name parameters

2024-02-06 05:41 UTC, Riddhiagrawal001 commented
> Why to remove named paramters? It's better to have name parameters

It was adding extra things we didn't need each time and due to that the switch case was a bit messy.

2024-02-06 07:17 UTC, PritishBudhiraja approved these changes

2024-02-06 09:26 UTC, JeevaRamu0104 approved these changes

2024-02-06 09:29 UTC, merged