feat: Added Counter disputes
juspay/hyperswitch-control-center pull request #347
Opened 2024-02-06 09:57 UTC by Riddhiagrawal001

## Type of Change

- [ ] Bugfix
- [X] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

## Motivation and Context

## How did you test it?

## Checklist

- [X] I ran `npm run re:build`
- [X] I reviewed submitted code
- [ ] I added unit tests for my changes where possible

2024-02-06 15:45 UTC, PritishBudhiraja requested changes

2024-02-06 15:45 UTC, PritishBudhiraja commented on src/screens/HyperSwitch/Disputes/UploadEvidenceForDisputes.res
> +            copyFileUploadedDict->Dict.set(keyValue, dictValue->Js.Json.object_)
Core API

2024-02-06 15:45 UTC, PritishBudhiraja commented on src/screens/HyperSwitch/Disputes/UploadEvidenceForDisputes.res
> +          let _err = Exn.message(e)->Option.getOr("Failed to Fetch!")
Use _

2024-02-06 15:45 UTC, PritishBudhiraja commented on src/screens/HyperSwitch/Disputes/UploadEvidenceForDisputes.res
> +                    leftIcon={Euler("paper-clip")}
Why Euler is still there?

2024-02-06 15:45 UTC, PritishBudhiraja commented on src/utils/LogicUtils.res
> +  let startDate = startDate->Js.Date.fromFloat
Core API

2024-02-06 15:45 UTC, PritishBudhiraja commented on src/utils/LogicUtils.res
> +  let endDate = endDate->Js.Date.fromFloat
Core API

2024-02-06 15:45 UTC, PritishBudhiraja commented on src/utils/LogicUtils.res
> +  let daysDiff = Math.abs(endDate->Js.Date.getTime -. startDate->Js.Date.getTime)
Core API

2024-02-07 06:08 UTC, Riddhiagrawal001 commented on src/screens/HyperSwitch/Disputes/UploadEvidenceForDisputes.res
> +        let res = acceptFile(ele, fileValue)
Assigning it to a variable and then returning it provides better code readability.

2024-02-07 06:13 UTC, PritishBudhiraja commented on src/screens/HyperSwitch/Disputes/UploadEvidenceForDisputes.res
> +        let res = acceptFile(ele, fileValue)
When we are using that then only else it's just unnecessary overhead

2024-02-07 06:52 UTC, PritishBudhiraja commented on src/screens/HyperSwitch/Disputes/UploadEvidenceForDisputes.res
> +          let _err = Exn.message(e)->Option.getOr("Failed to Fetch!")
```
 | _ => {
   showToast(
```

2024-02-07 08:13 UTC, Riddhiagrawal001 commented on src/screens/HyperSwitch/Disputes/UploadEvidenceForDisputes.res
> +        let res = acceptFile(ele, fileValue)
As this is return value from the function , its better to assign it to a variable and return

2024-02-08 05:19 UTC, PritishBudhiraja commented on src/screens/HyperSwitch/Disputes/UploadEvidenceForDisputes.res
> +          let _err = Exn.message(e)->Option.getOr("Failed to Fetch!")
Update this also

```
| _ => {
 showToast(
            ~message=`Failed to submit the evidence. Try again !`,
            ~toastType=ToastError,
            (),
          )
}
```

2024-02-14 07:44 UTC, JeevaRamu0104 commented on src/screens/HyperSwitch/Disputes/UploadEvidenceForDisputes.res
> +    let acceptFile = async (keyValue, fileValue) => {
remove the async

2024-02-14 07:44 UTC, JeevaRamu0104 commented on src/screens/HyperSwitch/Disputes/UploadEvidenceForDisputes.res
> +      let response = await updateDetails(
remove the await statement

2024-02-14 10:28 UTC, PritishBudhiraja approved these changes

2024-02-14 10:55 UTC, JeevaRamu0104 approved these changes

2024-02-14 11:41 UTC, merged